-- FASE 2 — correção de categorias TBCA mal classificadas no seed
-- (ex: pão de queijo era "vegetal", anchova era "condimento").
-- Gerado por scripts/generate-food-improvements.mjs. Regras por palavra-chave
-- no primeiro segmento do nome. Idempotente: UPDATE por (source, source_id).
-- Parte 3/3 (282 statements)

CREATE INDEX IF NOT EXISTS idx_global_foods_source_lookup ON fitness_global_foods(source, source_id);

UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0670N'; -- Papa de carne bovina moída (acém), fubá e espinafre, c/ cald (era suplemento)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0385N'; -- Papa de peito de frango, ervilha e abóbora (jerimum), c/ cal (era suplemento)
UPDATE fitness_global_foods SET categoria = 'carboidrato' WHERE source = 'tbca' AND source_id = 'C0128N'; -- Papa de batata, cenoura e carne moída (acém), c/ caldo de fr (era suplemento)
UPDATE fitness_global_foods SET categoria = 'fruta' WHERE source = 'tbca' AND source_id = 'C1039B'; -- Farofa de castanha de caju, c/ sal, (farinha de mandioca tor (era vegetal)
UPDATE fitness_global_foods SET categoria = 'carboidrato' WHERE source = 'tbca' AND source_id = 'C0866B'; -- Batata, inglesa, s/ casca, assada, alecrim, s/ óleo, c/ pime (era vegetal)
UPDATE fitness_global_foods SET categoria = 'bebida' WHERE source = 'tbca' AND source_id = 'C0041C'; -- Suco, laranja, Lima, s/ açúcar, Citrus sinensis (L.) Osbeck, (era fruta)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0235N'; -- Papa de fígado bovino e batata doce, c/ caldo de frango, c/  (era suplemento)
UPDATE fitness_global_foods SET categoria = 'condimento' WHERE source = 'tbca' AND source_id = 'C0716B'; -- Chicória do Pará (coentro bravo), cru, Eryngium cf. campestr (era vegetal)
UPDATE fitness_global_foods SET categoria = 'carboidrato' WHERE source = 'tbca' AND source_id = 'C0351B'; -- Cará, s/ casca, cozido, drenado, c/ óleo de soja, c/ sal, Di (era vegetal)
UPDATE fitness_global_foods SET categoria = 'carboidrato' WHERE source = 'tbca' AND source_id = 'C0408N'; -- Papa de batata, cenoura e carne bovina moída (patinho), c/ c (era suplemento)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0959B'; -- Quibebe, c/ sal, (abóbora, cabotian (japonesa), carne seca d (era vegetal)
UPDATE fitness_global_foods SET categoria = 'bebida' WHERE source = 'tbca' AND source_id = 'C0812B'; -- Molho de tomate, c/ proteína texturizada de soja, c/ óleo, c (era vegetal)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0274N'; -- Papa de peixe (pescada branca), abóbora (jerimum), batata-do (era suplemento)
UPDATE fitness_global_foods SET categoria = 'sobremesa' WHERE source = 'tbca' AND source_id = 'C0853B'; -- Bolo de mandioca (aipim, macaxeira) com carne, c/ sal, (mand (era vegetal)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0479N'; -- Papa de carne bovina moída (patinho), macarrão e brócolis, c (era suplemento)
UPDATE fitness_global_foods SET categoria = 'carboidrato' WHERE source = 'tbca' AND source_id = 'C0053L'; -- Lanche brasileiro (biscoito, doce, maisena, c/ café, infusão (era condimento)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0627N'; -- Papa de carne bovina moída (patinho), arroz branco e brócoli (era suplemento)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0228T'; -- Sopa, feijão preto, c/ carne bovina, c/ macarrão, c/ vegetai (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'bebida' WHERE source = 'tbca' AND source_id = 'C0845B'; -- Tomate recheado, c/ sal, (tomate, toucinho defumado (bacon), (era vegetal)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0294N'; -- Papa de carne bovina (músculo), feijão preto, batata, abóbor (era suplemento)
UPDATE fitness_global_foods SET categoria = 'bebida' WHERE source = 'tbca' AND source_id = 'C0101N'; -- Achocolatado, em pó, sem adição de açúcar, (era suplemento)
UPDATE fitness_global_foods SET categoria = 'bebida' WHERE source = 'tbca' AND source_id = 'C0129C'; -- Suco natural, laranja, mamão, pera e maçã, s/ açúcar, (era fruta)
UPDATE fitness_global_foods SET categoria = 'carboidrato' WHERE source = 'tbca' AND source_id = 'C0689B'; -- Batata suíça, c/ ricota e espinafre, c/ sal, (batata inglesa (era vegetal)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0892A'; -- Vatapá, c/ sal, (camarão seco dessalgado, leite de coco, ame (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0585N'; -- Papa de carne moída bovina (patinho), feijão preto, batata,  (era suplemento)
UPDATE fitness_global_foods SET categoria = 'condimento' WHERE source = 'tbca' AND source_id = 'C0115B'; -- Alho, cozido, s/ óleo, s/ sal, Allium sativum, (era vegetal)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0106N'; -- Papa de carne bovina moída (acém), fubá e couve, c/ caldo de (era suplemento)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0557N'; -- Papa de fígado bovino e batata doce, c/ caldo de carne, c/ c (era suplemento)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0939F'; -- Sopa, peito de frango e requeijão, c/ sal, (peito de frango, (era proteina)
UPDATE fitness_global_foods SET categoria = 'bebida' WHERE source = 'tbca' AND source_id = 'C0238C'; -- Suco natural, cacau, c/ açúcar, (era fruta)
UPDATE fitness_global_foods SET categoria = 'condimento' WHERE source = 'tbca' AND source_id = 'C1094B'; -- Cominho, semente, Cuminum cyminum, (era vegetal)
UPDATE fitness_global_foods SET categoria = 'carboidrato' WHERE source = 'tbca' AND source_id = 'C0140K'; -- Rocambole (farinha de trigo, ovo, leite, manteiga, açúcar e  (era sobremesa)
UPDATE fitness_global_foods SET categoria = 'carboidrato' WHERE source = 'tbca' AND source_id = 'C0781B'; -- Farofa, carne bovina, s/ sal, (farinha de mandioca (aipim, m (era vegetal)
UPDATE fitness_global_foods SET categoria = 'bebida' WHERE source = 'tbca' AND source_id = 'C0113C'; -- Suco natural, abacaxi, maracujá e caju, s/ açúcar, (era fruta)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0307A'; -- Sanduíche, pão forma tradicional, c/ presunto, c/ margarina, (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'condimento' WHERE source = 'tbca' AND source_id = 'C0830A'; -- Pão de alho, assado, (pão francês, maionese, alho, salsa, ce (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0556N'; -- Papa de fígado bovino e batata doce, c/ caldo de carne, c/ c (era suplemento)
UPDATE fitness_global_foods SET categoria = 'sobremesa' WHERE source = 'tbca' AND source_id = 'C0086R'; -- Manjar, coco, em pó, Ducoco, (era outros)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0234N'; -- Papa de fígado bovino e batata doce, c/ caldo de frango, c/  (era suplemento)
UPDATE fitness_global_foods SET categoria = 'carboidrato' WHERE source = 'tbca' AND source_id = 'C0863B'; -- Batata, inglesa, s/ casca, assada, alecrim, c/ manteiga, c/  (era vegetal)
UPDATE fitness_global_foods SET categoria = 'carboidrato' WHERE source = 'tbca' AND source_id = 'C0322N'; -- Papa de feijão preto, batata doce, abóbora cabotian (japones (era suplemento)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0756A'; -- Sanduíche, pão forma tradicional, c/ queijo minas, alface e  (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0843A'; -- Sanduíche, pão sírio, c/ peito de frango grelhado, alface am (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0867A'; -- Sushi, c/ pepino, (arroz para sushi (c/ vinagre de arroz, aç (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0340N'; -- Papa de carne bovina (músculo), feijão carioca, batata baroa (era suplemento)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0184N'; -- Papa de peito de frango, batata baroa (mandioquinha, salsa)  (era suplemento)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C1081A'; -- Pizza, calabresa, palmito e queijo muçarela, caseira, (massa (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0375A'; -- Sanduíche, peito de frango grelhado (c/ pão de hambúrguer),  (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'condimento' WHERE source = 'tbca' AND source_id = 'C0255B'; -- Mostarda, folha, refogada (c/ óleo, cebola e alho), s/ sal,  (era vegetal)
UPDATE fitness_global_foods SET categoria = 'carboidrato' WHERE source = 'tbca' AND source_id = 'C0417N'; -- Papa de batata, cenoura e carne bovina moída (acém), c/ cald (era suplemento)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0531N'; -- Papa de carne bovina moída (patinho), cenoura e batata baroa (era suplemento)
UPDATE fitness_global_foods SET categoria = 'sobremesa' WHERE source = 'tbca' AND source_id = 'C0001R'; -- Bolo, mistura p/ (média de diferentes sabores), (era outros)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0334N'; -- Papa de carne bovina (músculo), feijão preto, batata baroa ( (era suplemento)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0502A'; -- Sanduíche, vegetariano, pão forma integral, c/ alface, tomat (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'carboidrato' WHERE source = 'tbca' AND source_id = 'C1026B'; -- Nhoque, c/ molho bolonhesa, c/ sal, (batata, ovo, margarina  (era vegetal)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0070R'; -- Sopa, cebola, desidratada, Maggi, (era outros)
UPDATE fitness_global_foods SET categoria = 'carboidrato' WHERE source = 'tbca' AND source_id = 'C0209N'; -- Papa de feijão carioca, ovo e macarrão, c/ caldo de frango,  (era suplemento)
UPDATE fitness_global_foods SET categoria = 'sobremesa' WHERE source = 'tbca' AND source_id = 'C1001A'; -- Bolo, chocolate, c/ recheio, brigadeiro, caseiro, (bolo - fa (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'carboidrato' WHERE source = 'tbca' AND source_id = 'C0677N'; -- Papa de feijão preto, abobrinha e beterraba, c/ caldo de fra (era suplemento)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0287A'; -- Sanduíche, queijo quente, pão forma integral, c/ queijo prat (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0302N'; -- Papa de carne bovina (músculo), feijão carioca, batata, abób (era suplemento)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0500A'; -- Sanduíche, pão forma integral, c/ alface, tomate, sardinha e (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'bebida' WHERE source = 'tbca' AND source_id = 'C0250C'; -- Suco, néctar, manga, c/ suco de maçã, c/ açúcar, (era fruta)
UPDATE fitness_global_foods SET categoria = 'carboidrato' WHERE source = 'tbca' AND source_id = 'C0111B'; -- Nhoque (batata, ovo, margarina e farinha de trigo), cozido,  (era vegetal)
UPDATE fitness_global_foods SET categoria = 'carboidrato' WHERE source = 'tbca' AND source_id = 'C0865B'; -- Batata, inglesa, s/ casca, assada, alecrim, c/ azeite de oli (era vegetal)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0841A'; -- Sanduíche, hambúrguer bovino grelhado (c/ pão hambúrguer), c (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0221N'; -- Papa de carne bovina moída (acém), abóbora (jerimum) e chuch (era suplemento)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0119N'; -- Papa de peito de frango, batata doce e abobrinha, c/ caldo d (era suplemento)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0453N'; -- Papa de carne bovina moída (acém), abóbora (jerimum) e chuch (era suplemento)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0916F'; -- Sarapatel (arrasto suíno), c/ sal, (vísceras de porco, coraç (era proteina)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0774B'; -- Bobó de frango, s/ sal, (mandioca (aipim, macaxeira), peito  (era vegetal)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0304A'; -- Sanduíche, pão forma integral, c/ presunto, c/ maionese, (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'condimento' WHERE source = 'tbca' AND source_id = 'C0915F'; -- Frango com açafrão (cúrcuma), c/ sal, (carne de frango, coxa (era proteina)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0253N'; -- Papa de ovo e batata, c/ caldo de frango, c/ cebola, s/ óleo (era suplemento)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0392N'; -- Papa de carne bovina moída (acém), fubá e couve, c/ caldo de (era suplemento)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0237N'; -- Papa de peito de frango e inhame, c/ caldo de frango, c/ ceb (era suplemento)
UPDATE fitness_global_foods SET categoria = 'condimento' WHERE source = 'tbca' AND source_id = 'C0921B'; -- Cebolinha, verde, cozida, s/ óleo, c/ sal, (era vegetal)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C1141A'; -- Sanduíche, pão ciabatta, c/ tofu, queijo vegetal de castanha (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'carboidrato' WHERE source = 'tbca' AND source_id = 'C0908B'; -- Mandioca (aipim, macaxeira), s/ casca, cozida, drenada, s/ ó (era vegetal)
UPDATE fitness_global_foods SET categoria = 'bebida' WHERE source = 'tbca' AND source_id = 'C0001G'; -- Bebida láctea (média de diferentes sabores), (era laticinio)
UPDATE fitness_global_foods SET categoria = 'carboidrato' WHERE source = 'tbca' AND source_id = 'C0569F'; -- Sangue, porco, cru, (era proteina)
UPDATE fitness_global_foods SET categoria = 'laticinio' WHERE source = 'tbca' AND source_id = 'C0809B'; -- Pirão de leite, c/ sal, (leite, farinha de mandioca (aipim,  (era vegetal)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0466N'; -- Papa de peito de frango, fubá e couve, c/ caldo de frango, c (era suplemento)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0667N'; -- Papa de carne bovina moída (acém), fubá e espinafre, c/ cald (era suplemento)
UPDATE fitness_global_foods SET categoria = 'carboidrato' WHERE source = 'tbca' AND source_id = 'C0636N'; -- Papa de feijão preto, batata doce, abóbora cabotian (japones (era suplemento)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0218N'; -- Papa de carne bovina moída (acém), abóbora (jerimum) e chuch (era suplemento)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0561N'; -- Papa de fígado bovino e batata doce, c/ caldo de carne, c/ c (era suplemento)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C1086A'; -- Sanduíche, pão forma integral, c/ manteiga, s/ sal, (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'carboidrato' WHERE source = 'tbca' AND source_id = 'C0311N'; -- Papa de feijão carioca, batata, abóbora (jerimum) e cenoura, (era suplemento)
UPDATE fitness_global_foods SET categoria = 'carboidrato' WHERE source = 'tbca' AND source_id = 'C0788B'; -- Farofa, ovos, c sal, (farinha de mandioca (aipim, macaxeira) (era vegetal)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0468N'; -- Papa de peito de frango, fubá e couve, c/ caldo de frango, c (era suplemento)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0891B'; -- Sopa, canja, c/ legumes, c/ arroz polido, c/ peito de frango (era vegetal)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0558N'; -- Papa de fígado bovino e batata doce, c/ caldo de carne, c/ c (era suplemento)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0489N'; -- Papa de carne bovina moída (patinho), cenoura e batata baroa (era suplemento)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0276A'; -- Sanduíche, queijo quente, pão forma integral, c/ queijo muça (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'carboidrato' WHERE source = 'tbca' AND source_id = 'C0054B'; -- Batata, baroa (mandioquinha, batata salsa), s/ casca, cozida (era vegetal)
UPDATE fitness_global_foods SET categoria = 'condimento' WHERE source = 'tbca' AND source_id = 'C0465B'; -- Pimentão, cozido, drenado, s/ óleo, s/ sal, Capsicum annuum  (era vegetal)
UPDATE fitness_global_foods SET categoria = 'carboidrato' WHERE source = 'tbca' AND source_id = 'C0308B'; -- Mandioca (aipim, macaxeira), s/ casca, cozida, c/ óleo de so (era vegetal)
UPDATE fitness_global_foods SET categoria = 'fruta' WHERE source = 'tbca' AND source_id = 'C0316N'; -- Papa de banana e maçã, c/ aveia em flocos, s/ açúcar, (era suplemento)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0318A'; -- Sanduíche, hambúrguer grelhado (c/ pão hambúrguer), c/ alfac (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'laticinio' WHERE source = 'tbca' AND source_id = 'C1111A'; -- Arroz de leite, (arroz integral, leite integral, c/ óleo de  (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0642N'; -- Papa de peito de frango, batata e cenoura, c/ caldo de carne (era suplemento)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0429A'; -- Pizza, portuguesa, caseira, (massa (farinha de trigo, óleo,  (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'carboidrato' WHERE source = 'tbca' AND source_id = 'C0208N'; -- Papa de feijão carioca, ovo e macarrão, c/ caldo de frango,  (era suplemento)
UPDATE fitness_global_foods SET categoria = 'fruta' WHERE source = 'tbca' AND source_id = 'C0671N'; -- Papa de ameixa e mamão, c/ aveia em flocos, s/ açúcar, (era suplemento)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0495N'; -- Papa de carne bovina moída (patinho), abóbora (jerimum) e ch (era suplemento)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0760A'; -- Sanduíche, pão forma tradicional, c/ ricota e temperos, alfa (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'condimento' WHERE source = 'tbca' AND source_id = 'C0246F'; -- Molho, à bolonhesa (25% de carne moída), c/ sal, (carne, boi (era proteina)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0886A'; -- Sopa instantânea, c/ macarrão, (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'bebida' WHERE source = 'tbca' AND source_id = 'C0022C'; -- Suco, limão, Tahiti, s/ açúcar (s/ diluição em água), Citrus (era fruta)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0961B'; -- Tabule, c/ sal, (trigo para quibe, pepino, cebola, tomate, s (era vegetal)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C1058A'; -- Sopa, carne bovina, c/ macarrão, c/ vegetais, c/ sal, (carne (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'carboidrato' WHERE source = 'tbca' AND source_id = 'C0123B'; -- Pão, de queijo, industrializado, assado, (era vegetal)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0115N'; -- Papa de fígado bovino, batata e cenoura, c/ caldo de frango, (era suplemento)
UPDATE fitness_global_foods SET categoria = 'carboidrato' WHERE source = 'tbca' AND source_id = 'C0135N'; -- Papa de feijão preto, macarrão e chicória, c/ caldo de frang (era suplemento)
UPDATE fitness_global_foods SET categoria = 'sobremesa' WHERE source = 'tbca' AND source_id = 'C1073A'; -- Bolo de cenoura, c/ cobertura de chocolate e leite de coco,  (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0665A'; -- Sopa, milho, fubá, c/ couve, c/ sal, (milho, fubá, couve, c/ (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0866A'; -- Sanduíche, cheese salada, hambúrguer bovino grelhado (c/ pão (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'condimento' WHERE source = 'tbca' AND source_id = 'C0243B'; -- Mostarda, cozida, drenada, c/ óleo de soja, s/ sal, Brassica (era vegetal)
UPDATE fitness_global_foods SET categoria = 'bebida' WHERE source = 'tbca' AND source_id = 'C0166C'; -- Suco, concentrado, preparado, uva, c/ açúcar, suco concentra (era fruta)
UPDATE fitness_global_foods SET categoria = 'condimento' WHERE source = 'tbca' AND source_id = 'C0731B'; -- Caldo de cogumelos, caseiro, s/ óleo, s/ sal, (shiitake, c/  (era vegetal)
UPDATE fitness_global_foods SET categoria = 'gordura' WHERE source = 'tbca' AND source_id = 'C0194E'; -- peixe agua salgada merluza frito oleo soja sal, Merlucius hu (era proteina)
UPDATE fitness_global_foods SET categoria = 'sobremesa' WHERE source = 'tbca' AND source_id = 'C0184A'; -- Canjica, milho, branca, cozida, c/ leite integral e açúcar, (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0559N'; -- Papa de fígado bovino e batata doce, c/ caldo de carne, c/ c (era suplemento)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0921F'; -- Quibe, bovino, cru, c/ sal, (trigo para quibe, carne bovina  (era proteina)
UPDATE fitness_global_foods SET categoria = 'carboidrato' WHERE source = 'tbca' AND source_id = 'C0125N'; -- Papa de batata, cenoura e carne moída bovina (acém), c/ cald (era suplemento)
UPDATE fitness_global_foods SET categoria = 'vegetal' WHERE source = 'tbca' AND source_id = 'C0115T'; -- Vagem, cozida, drenada, c/ óleo de soja, c/ sal, Phaseolus v (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'carboidrato' WHERE source = 'tbca' AND source_id = 'C0094B'; -- Pão, de queijo, industrializado, cru, (era vegetal)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0482N'; -- Papa de carne bovina moída (patinho), macarrão e brócolis, c (era suplemento)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0319A'; -- Sanduíche, pão forma tradicional, c/ margarina, c/ sal, (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0114N'; -- Papa de fígado bovino, batata e cenoura, c/ caldo de frango, (era suplemento)
UPDATE fitness_global_foods SET categoria = 'vegetal' WHERE source = 'tbca' AND source_id = 'C0293E'; -- Frutos do mar com legumes, s/ sal, (frutos do mar - camarão, (era proteina)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0769A'; -- Sanduíche, pão sírio, c/ alface, tomate, cenoura e pepino, (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0143N'; -- Papa de carne bovina (músculo), feijão carioca, batata, abób (era suplemento)
UPDATE fitness_global_foods SET categoria = 'sobremesa' WHERE source = 'tbca' AND source_id = 'C0050R'; -- Pudim,  caramelo, mistura p/, Oetker, (era outros)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0737B'; -- Sopa de entulho, c/ carne e vegetais, c/ feijão vermelho, s/ (era vegetal)
UPDATE fitness_global_foods SET categoria = 'carboidrato' WHERE source = 'tbca' AND source_id = 'C0305N'; -- Papa de feijão preto, batata, abóbora (jerimum) e cenoura, c (era suplemento)
UPDATE fitness_global_foods SET categoria = 'carboidrato' WHERE source = 'tbca' AND source_id = 'C0683B'; -- Lasanha, berinjela, c/ frios, caseira, s/ sal, (berinjela gr (era vegetal)
UPDATE fitness_global_foods SET categoria = 'carboidrato' WHERE source = 'tbca' AND source_id = 'C0136N'; -- Papa de feijão carioca, macarrão e chicória, c/ caldo de fra (era suplemento)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0203A'; -- Vatapá, s/ sal, (camarão seco dessalgado, leite de coco, ame (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0310A'; -- Sanduíche, pão francês, c/ mortadela, c/ manteiga, (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0539N'; -- Papa de carne bovina moída (patinho), cará e brócolis, c/ ca (era suplemento)
UPDATE fitness_global_foods SET categoria = 'sobremesa' WHERE source = 'tbca' AND source_id = 'C0093G'; -- Mousse de camarão, (camarão cozido, gelatina s/ sabor, maion (era laticinio)
UPDATE fitness_global_foods SET categoria = 'sobremesa' WHERE source = 'tbca' AND source_id = 'C1003A'; -- Bolo, limão, caseiro, simples, (farinha de trigo, suco de li (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'condimento' WHERE source = 'tbca' AND source_id = 'C0775B'; -- Coentro, folha, cru, Coriandrum sativum, (era vegetal)
UPDATE fitness_global_foods SET categoria = 'carboidrato' WHERE source = 'tbca' AND source_id = 'C0297B'; -- Batata, baroa (mandioquinha, batata salsa), cozida, s/ casca (era vegetal)
UPDATE fitness_global_foods SET categoria = 'sobremesa' WHERE source = 'tbca' AND source_id = 'C0067A'; -- Bolo, laranja, mistura p/, preparado, Oetker, (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'sobremesa' WHERE source = 'tbca' AND source_id = 'C0459A'; -- Bolo, mandioca (aipim, macaxeira), c/ coco, simples, caseiro (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0502N'; -- Papa de carne bovina moída (acém), batata e abóbora cabotian (era suplemento)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0437N'; -- Papa de carne bovina moída (acém), macarrão e brócolis, c/ c (era suplemento)
UPDATE fitness_global_foods SET categoria = 'sobremesa' WHERE source = 'tbca' AND source_id = 'C0061R'; -- Sagu, framboesa, mistura p/, Ducoco, (era outros)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0384A'; -- Sanduíche, baguete, c/ queijo muçarela, alface, tomate, peit (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0533A'; -- Arroz com linguiça, c/ arroz integral, s/ sal, (arroz integr (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0349N'; -- Papa de carne bovina moída (acém), arroz e brócolis, c/ cald (era suplemento)
UPDATE fitness_global_foods SET categoria = 'carboidrato' WHERE source = 'tbca' AND source_id = 'C0012B'; -- Batata, doce, s/ casca, crua, Ipomea batatas (L.) Lam, (era vegetal)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0439A'; -- Esfirra, caseira, assada (média de diversos sabores - carne, (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'sobremesa' WHERE source = 'tbca' AND source_id = 'C1149A'; -- Bolo, trigo, caseiro, c/ recheio e cobertura, chantilly, mor (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0332A'; -- Sanduíche, pão forma integral, c/ peito de peru defumado, qu (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'sobremesa' WHERE source = 'tbca' AND source_id = 'C0005N'; -- Gelatina, cereja, em pó, diet, Ducocco, (era suplemento)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0757A'; -- Sanduíche, pão sírio, c/ queijo minas, alface e tomate, (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0597N'; -- Papa de peixe (pescada branca), abóbora (jerimum), batata do (era suplemento)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0503N'; -- Papa de peito de frango, fubá e couve, c/ caldo de carne, c/ (era suplemento)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0345A'; -- Sanduíche, pão francês, c/ peito de peru defumado, queijo mu (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0120N'; -- Papa de peito de frango, batata doce e abobrinha, c/ caldo d (era suplemento)
UPDATE fitness_global_foods SET categoria = 'sobremesa' WHERE source = 'tbca' AND source_id = 'C0854B'; -- Bolo de mandioca (aipim, macaxeira) com carne, s/ sal, (mand (era vegetal)
UPDATE fitness_global_foods SET categoria = 'carboidrato' WHERE source = 'tbca' AND source_id = 'C0684N'; -- Papa de feijão carioca, abobrinha e beterraba, c/ caldo de f (era suplemento)
UPDATE fitness_global_foods SET categoria = 'bebida' WHERE source = 'tbca' AND source_id = 'C0152C'; -- Suco, polpa, congelada, preparado, cupuaçu, c/ açúcar, (era fruta)
UPDATE fitness_global_foods SET categoria = 'bebida' WHERE source = 'tbca' AND source_id = 'C0048N'; -- Refrigerante, tipo água tônica, c/ adoçante, (era suplemento)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0763A'; -- Sanduíche, pão forma integral, c/ alface, tomate, cenoura, c (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0848A'; -- Sanduíche, hambúrguer bovino grelhado (c/ pão hambúrguer), c (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0397N'; -- Papa de carne bovina moída (patinho), fubá e couve, c/ caldo (era suplemento)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0611N'; -- Papa de carne bovina moída (acém), arroz branco e brócolis,  (era suplemento)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0198N'; -- Papa de carne bovina moída (acém), macarrão e brócolis, c/ c (era suplemento)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0167N'; -- Papa de peito de frango, inhame e beterraba, c/ caldo de fra (era suplemento)
UPDATE fitness_global_foods SET categoria = 'bebida' WHERE source = 'tbca' AND source_id = 'C0033U'; -- Bebida, substituto do leite b bebida vegetal à base de amênd (era gordura)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0234T'; -- Sopa, feijão preto, c/ carne bovina, c/ macarrão, c/ vegetai (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0096N'; -- Pizza, portuguesa, light, caseira, (massa (farinha de trigo, (era suplemento)
UPDATE fitness_global_foods SET categoria = 'vegetal' WHERE source = 'tbca' AND source_id = 'C0938A'; -- Salada, macarrão de arroz, c/ pepino e cenoura, c/ presunto, (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'carboidrato' WHERE source = 'tbca' AND source_id = 'C0284C'; -- Fruta pão, cozida, s/ manteiga, s/ açúcar, (era fruta)
UPDATE fitness_global_foods SET categoria = 'condimento' WHERE source = 'tbca' AND source_id = 'C0468B'; -- Pimentão, amarelo, cozido, drenado, s/ óleo, c/ sal, Capsicu (era vegetal)
UPDATE fitness_global_foods SET categoria = 'fruta' WHERE source = 'tbca' AND source_id = 'C0426N'; -- Papa de goiaba e banana, s/ açúcar, (era suplemento)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0249A'; -- Sanduíche, hambúrguer bovino grelhado (c/ pão hambúrguer), c (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'condimento' WHERE source = 'tbca' AND source_id = 'C0121B'; -- Azeitona, verde, conserva, drenada, Olea europaea L., (era vegetal)
UPDATE fitness_global_foods SET categoria = 'condimento' WHERE source = 'tbca' AND source_id = 'C0373E'; -- Caldo de camarão, (camarão, c/ cebola, cenoura, aipo (salsão (era proteina)
UPDATE fitness_global_foods SET categoria = 'sobremesa' WHERE source = 'tbca' AND source_id = 'C0081N'; -- Bolo, chocolate, simples, diet, caseiro, (farinha de trigo,  (era suplemento)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0491N'; -- Papa de carne bovina moída (patinho), abóbora (jerimum) e ch (era suplemento)
UPDATE fitness_global_foods SET categoria = 'carboidrato' WHERE source = 'tbca' AND source_id = 'C0124N'; -- Papa de batata, cenoura e carne moída bovina (acém), c/ cald (era suplemento)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0436N'; -- Papa de carne bovina moída (acém), macarrão e brócolis, c/ c (era suplemento)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0478N'; -- Papa de carne bovina moída (patinho), macarrão e brócolis, c (era suplemento)
UPDATE fitness_global_foods SET categoria = 'sobremesa' WHERE source = 'tbca' AND source_id = 'C0027N'; -- Pudim, coco, mistura p/, diet, Ducoco, (era suplemento)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0227F'; -- Sarapatel (arrasto suíno), s/ sal, (vísceras de porco, coraç (era proteina)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0514N'; -- Papa de carne bovina moída (patinho) e abóbora cabotian (jap (era suplemento)
UPDATE fitness_global_foods SET categoria = 'bebida' WHERE source = 'tbca' AND source_id = 'C0149C'; -- Suco natural, acerola, s/ açúcar, (era fruta)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0273A'; -- Sanduíche, queijo quente, pão francês, c/ queijo muçarela e  (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'sobremesa' WHERE source = 'tbca' AND source_id = 'C0022N'; -- Pudim, mistura p/, diet (média de diferentes sabores), (era suplemento)
UPDATE fitness_global_foods SET categoria = 'carboidrato' WHERE source = 'tbca' AND source_id = 'C0091N'; -- Massa brise, light, assada, (farinha de trigo, manteiga ligh (era suplemento)
UPDATE fitness_global_foods SET categoria = 'bebida' WHERE source = 'tbca' AND source_id = 'C0052N'; -- Refrigerante, tipo limão, c/ adoçante, (era suplemento)
UPDATE fitness_global_foods SET categoria = 'gordura' WHERE source = 'tbca' AND source_id = 'C0020T'; -- Amendoim, grão, cru, Arachis hypogaea L., (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0667A'; -- Sopa, milho, fubá, c/ couve, s/ sal, (milho, fubá, couve, c/ (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0446N'; -- Papa de carne bovina moída (acém), cenoura e batata baroa (m (era suplemento)
UPDATE fitness_global_foods SET categoria = 'gordura' WHERE source = 'tbca' AND source_id = 'C0150G'; -- Manteiga de garrafa, artesanal (média de diferentes regions) (era laticinio)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0041E'; -- Peixe, água salgada, anchova, filé,  fresco,  Pomatus saltat (era condimento)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0581N'; -- Papa de carne moída bovina (patinho), feijão preto, batata,  (era suplemento)
UPDATE fitness_global_foods SET categoria = 'bebida' WHERE source = 'tbca' AND source_id = 'C0968B'; -- Tomate, maduro, assado, s/ óleo, c/ sal, (era vegetal)
UPDATE fitness_global_foods SET categoria = 'carboidrato' WHERE source = 'tbca' AND source_id = 'C0310N'; -- Papa de feijão carioca, batata, abóbora (jerimum) e cenoura, (era suplemento)
UPDATE fitness_global_foods SET categoria = 'carboidrato' WHERE source = 'tbca' AND source_id = 'C0920B'; -- Nhoque (batata, ovo, margarina e farinha de trigo), cozido,  (era vegetal)
UPDATE fitness_global_foods SET categoria = 'carboidrato' WHERE source = 'tbca' AND source_id = 'C0328N'; -- Papa de feijão carioca, batata doce, abóbora cabotian (japon (era suplemento)
UPDATE fitness_global_foods SET categoria = 'carboidrato' WHERE source = 'tbca' AND source_id = 'C1103B'; -- Lasanha vegana, c/ abobrinha, s/ sal, (abobrinha, tomate, ca (era vegetal)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0280N'; -- Papa de peixe (pescada branca) e batata, c/ caldo de frango, (era suplemento)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C1167A'; -- Pizza, massa fina, liguiça calabresa e queijo muçarela, case (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0353A'; -- Sanduíche, pão forma tradicional, c/ peito de peru defumado, (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'carboidrato' WHERE source = 'tbca' AND source_id = 'C0298B'; -- Batata, doce, s/ casca, cozida, drenada, c/ óleo de soja, s/ (era vegetal)
UPDATE fitness_global_foods SET categoria = 'sobremesa' WHERE source = 'tbca' AND source_id = 'C0858B'; -- Bolo de batata doce com carne, s/ sal, (batata doce, ovo, ma (era vegetal)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0237T'; -- Sopa, feijão preto, c/ macarrão, c/ vegetais, s/ sal, (feijã (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'bebida' WHERE source = 'tbca' AND source_id = 'C0135C'; -- Suco, concentrado, preparado, caju, s/ açúcar, (era fruta)
UPDATE fitness_global_foods SET categoria = 'bebida' WHERE source = 'tbca' AND source_id = 'C0150C'; -- Suco natural, acerola, c/ açúcar, (era fruta)
UPDATE fitness_global_foods SET categoria = 'carboidrato' WHERE source = 'tbca' AND source_id = 'C0637N'; -- Papa de feijão preto, batata doce, abóbora cabotian (japones (era suplemento)
UPDATE fitness_global_foods SET categoria = 'sobremesa' WHERE source = 'tbca' AND source_id = 'C0461A'; -- Bolo, cenoura, simples, caseiro, (farinha de trigo, cenoura, (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0259A'; -- Sanduíche, americano (pão forma integral), c/ presunto, quei (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0494N'; -- Papa de carne bovina moída (patinho), abóbora (jerimum) e ch (era suplemento)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0505F'; -- Sopa, carne bovina, c/ macarrão, c/ vegetais, c/ sal, (carne (era vegetal)
UPDATE fitness_global_foods SET categoria = 'sobremesa' WHERE source = 'tbca' AND source_id = 'C1000A'; -- Bolo, chocolate, c/ cobertura, chocolate, caseiro, (farinha  (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'condimento' WHERE source = 'tbca' AND source_id = 'C0389E'; -- Camarão com molho branco (farinha de trigo, manteiga e leite (era proteina)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0354A'; -- Sanduíche, pão forma integral, c/ peito de peru defumado, qu (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0430N'; -- Papa de carne bovina moída (acém) e abóbora cabotian (japone (era suplemento)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0194N'; -- Papa de carne bovina moída (acém), macarrão e brócolis, c/ c (era suplemento)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0411A'; -- Sanduíche, americano (pão francês, c/ presunto, queijo muçar (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0232N'; -- Papa de fígado bovino e batata doce, c/ caldo de frango, c/  (era suplemento)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0238N'; -- Papa de peito de frango e inhame, c/ caldo de frango, c/ ceb (era suplemento)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0243A'; -- Sanduíche, cachorro quente (c/ pão hot dog e salsicha), c/ m (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'sobremesa' WHERE source = 'tbca' AND source_id = 'C0014N'; -- Gelatina, em pó, preparada, diet (média de diferentes sabore (era suplemento)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0266A'; -- Sanduíche, misto quente, pão francês, c/ presunto, queijo mu (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0395N'; -- Papa de carne bovina moída (patinho), fubá e couve, c/ caldo (era suplemento)
UPDATE fitness_global_foods SET categoria = 'carboidrato' WHERE source = 'tbca' AND source_id = 'C0692N'; -- Papa de feijão carioca, abobrinha e beterraba, c/ caldo de c (era suplemento)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0442N'; -- Papa de carne bovina moída (acém), cenoura e batata baroa (m (era suplemento)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0125B'; -- Sopa, creme, ervilha, industrializada, congelada, preparada, (era vegetal)
UPDATE fitness_global_foods SET categoria = 'carboidrato' WHERE source = 'tbca' AND source_id = 'C0690B'; -- Batata recheada, c/ requeijão e toucinho defumado (bacon), a (era vegetal)
UPDATE fitness_global_foods SET categoria = 'gordura' WHERE source = 'tbca' AND source_id = 'C0263T'; -- Amendoim, japonês, caseiro, (amenoim, farinha de trigo, água (era condimento)
UPDATE fitness_global_foods SET categoria = 'carboidrato' WHERE source = 'tbca' AND source_id = 'C0795B'; -- Farofa, couve com toucinho defumado (bacon), s/ sal, (farinh (era vegetal)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C1107A'; -- Pizza, ricota com nozes, caseira, (massa (farinha de trigo,  (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0497A'; -- Sanduíche, pão francês, c/ filé mignon grelhada, rúcula, tom (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'sobremesa' WHERE source = 'tbca' AND source_id = 'C0007N'; -- Gelatina, framboesa, em pó, diet, Ducocco, (era suplemento)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0240N'; -- Papa de peito de frango e inhame, c/ caldo de frango, c/ ceb (era suplemento)
UPDATE fitness_global_foods SET categoria = 'sobremesa' WHERE source = 'tbca' AND source_id = 'C0859B'; -- Bolo de batata doce com frango, c/ sal, (batata doce, ovo, m (era vegetal)
UPDATE fitness_global_foods SET categoria = 'bebida' WHERE source = 'tbca' AND source_id = 'C0139C'; -- Suco natural, mamão, s/ açúcar, (era fruta)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0484N'; -- Papa de carne bovina moída (patinho), cenoura e batata baroa (era suplemento)
UPDATE fitness_global_foods SET categoria = 'condimento' WHERE source = 'tbca' AND source_id = 'C0332E'; -- Mexilhão com molho branco (farinha de trigo, manteiga e leit (era proteina)
UPDATE fitness_global_foods SET categoria = 'condimento' WHERE source = 'tbca' AND source_id = 'C0125T'; -- Caldo de feijão, c/ sal, (feijão preto, c/ óleo, cebola e al (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'carboidrato' WHERE source = 'tbca' AND source_id = 'C0862B'; -- Batata, inglesa, s/ casca, assada, alecrim, c/ manteiga, c/  (era vegetal)
UPDATE fitness_global_foods SET categoria = 'sobremesa' WHERE source = 'tbca' AND source_id = 'C0065A'; -- Bolo, chocolate, mistura p/, preparado, Oetker, (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'carboidrato' WHERE source = 'tbca' AND source_id = 'C0910B'; -- Cará, cozido, drenada, s/ óleo, c/ sal, Dioscorea alata L., (era vegetal)
UPDATE fitness_global_foods SET categoria = 'bebida' WHERE source = 'tbca' AND source_id = 'C0142C'; -- Suco natural, manga, c/ açúcar, (era fruta)
UPDATE fitness_global_foods SET categoria = 'bebida' WHERE source = 'tbca' AND source_id = 'C0156C'; -- Suco natural, laranja e beterraba, c/ açúcar, (era fruta)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0877F'; -- Quibe, bovino, frito, c/sal, (era proteina)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0199N'; -- Papa de carne bovina moída (acém), macarrão e brócolis, c/ c (era suplemento)
UPDATE fitness_global_foods SET categoria = 'fruta' WHERE source = 'tbca' AND source_id = 'C0116K'; -- Cajuzinho, (leite condensado, amendoin torrado, manteiga, c/ (era sobremesa)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0268B'; -- Sopa, abóbora, cabotian (japonesa), c/ sal, (abóbora, caboti (era vegetal)
UPDATE fitness_global_foods SET categoria = 'carboidrato' WHERE source = 'tbca' AND source_id = 'C0633N'; -- Papa de feijão carioca, batata doce, abóbora cabotian (japon (era suplemento)
UPDATE fitness_global_foods SET categoria = 'vegetal' WHERE source = 'tbca' AND source_id = 'C0067T'; -- Vagem, macarrão, crua, Phaseolus vulgaris L., (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'sobremesa' WHERE source = 'tbca' AND source_id = 'C0823A'; -- Bolo, chocolate, c/ recheio de brigadeiro, c/ cobertura de c (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'bebida' WHERE source = 'tbca' AND source_id = 'C0224C'; -- Suco, néctar, pêssego, (era fruta)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C1029A'; -- Arroz com carne bovina, c/ arroz polido, c/ sal, (arroz poli (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0255A'; -- Sanduíche, pão francês, c/ presunto, queijo muçarela, alface (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0191N'; -- Papa de carne bovina moída (acém) e abóbora cambotian (japon (era suplemento)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0265N'; -- Papa de peito de frango e batata doce, c/ caldo de frango, c (era suplemento)
UPDATE fitness_global_foods SET categoria = 'laticinio' WHERE source = 'tbca' AND source_id = 'C0074N'; -- Queijo, muçarela, light, (era suplemento)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0570N'; -- Papa de carne moída bovina (patinho), feijão preto, batata,  (era suplemento)
UPDATE fitness_global_foods SET categoria = 'bebida' WHERE source = 'tbca' AND source_id = 'C0162C'; -- Suco, limonada, c/ açúcar, (era fruta)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0617N'; -- Papa de carne bovina moída (patinho), arroz branco e brócoli (era suplemento)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0735B'; -- Sopa, vegetais, s/ sal, (cenoura, abobrinha, brócolis e inha (era vegetal)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0770B'; -- Bobó de camarão, s/ sal, (mandioca (aipim, macaxeira), camar (era vegetal)
UPDATE fitness_global_foods SET categoria = 'sobremesa' WHERE source = 'tbca' AND source_id = 'C0057R'; -- Pudim, leite, c/ calda caramelo, mistura p/, Oetker, (era outros)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0251N'; -- Papa de ovo e batata, c/ caldo de frango, c/ cebola e azeite (era suplemento)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0606N'; -- Papa de peixe (pescada branca) e cará, c/ caldo de peixe, c/ (era suplemento)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0218F'; -- Strogonoff, frango, congelado, c/ temperos, c/ sal, Sadia, (era proteina)
UPDATE fitness_global_foods SET categoria = 'vegetal' WHERE source = 'tbca' AND source_id = 'C0174T'; -- Salada, grão-de-bico, c/ azeite de oliva, c/ sal, ( grão-de- (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'condimento' WHERE source = 'tbca' AND source_id = 'C0472B'; -- Pimentão, vermelho, cozido, drenado, s/ óleo, c/ sal, Capsic (era vegetal)
UPDATE fitness_global_foods SET categoria = 'sobremesa' WHERE source = 'tbca' AND source_id = 'C1007A'; -- Bolo, trigo, c/ recheio e cobertura, chantilly, morango e me (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'proteina' WHERE source = 'tbca' AND source_id = 'C0246N'; -- Papa de ovo e batata baroa (mandioquinha, batata salsa), c/  (era suplemento)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0677A'; -- Pizza, atum, caseira, (massa (farinha de trigo, óleo, fermen (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'prato_pronto' WHERE source = 'tbca' AND source_id = 'C0764A'; -- Sanduíche, pão forma tradicional, c/ alface, tomate, cenoura (era carboidrato)
UPDATE fitness_global_foods SET categoria = 'fruta' WHERE source = 'tbca' AND source_id = 'C0428N'; -- Papa de abacate e banana, s/ açúcar, (era suplemento)
